// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQk0OOJKp822txbavb7MpFQKEHCP1Ub5s',
    appId: '1:174950507681:web:506c429422feddcd707ce0',
    messagingSenderId: '174950507681',
    projectId: 'halifax-dating',
    authDomain: 'halifax-dating.firebaseapp.com',
    storageBucket: 'halifax-dating.appspot.com',
    measurementId: 'G-30J5T9BL77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgPxDd9Tl7JW8y8EwOgweiHRaFbeUbb5E',
    appId: '1:174950507681:android:1b6d4fd405e8b37c707ce0',
    messagingSenderId: '174950507681',
    projectId: 'halifax-dating',
    storageBucket: 'halifax-dating.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXCEOGsP97e-lqLPYO9Hv3e1b1e31Exb8',
    appId: '1:174950507681:ios:70a611abf04c339f707ce0',
    messagingSenderId: '174950507681',
    projectId: 'halifax-dating',
    storageBucket: 'halifax-dating.appspot.com',
    iosBundleId: 'com.example.halifaxDating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXCEOGsP97e-lqLPYO9Hv3e1b1e31Exb8',
    appId: '1:174950507681:ios:ac298452f4c4f48f707ce0',
    messagingSenderId: '174950507681',
    projectId: 'halifax-dating',
    storageBucket: 'halifax-dating.appspot.com',
    iosBundleId: 'com.example.halifaxDating.RunnerTests',
  );
}
